runner:
  plugin: threaded
  options:
    num_workers: 20       # 最大并发数

inventory:
  plugin: YAMLInventory
  options:
    hosts_file: "inventories/hosts.yaml"
    groups_file: "inventories/default.yaml"
    defaults_file: "inventories/default.yaml"
