r1:
  hostname: "192.168.1.1"
  username: "admin"
  password: "password"
  platform: "cisco_ios"
  commands:  # 为设备 r1 指定其命令集
    - "show version"
    - "show ip interface brief"

r2:
  hostname: "192.168.1.2"
  username: "admin"
  password: "password"
  platform: "cisco_ios"
  commands:  # 为设备 r2 指定其命令集
    - "show running-config"
    - "show arp"
