core_sw1:
  hostname: 192.168.1.1
  platform: huawei_vrp
  groups: [beijing_dc]
  custom_commands:
    get_config: 
      - display saved-configuration
      - display version

edge_rt1:
  hostname: 10.1.1.254
  platform: cisco_ios
  groups: [shanghai_branch]
  port: 2222
