name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'  # 标签触发(例如 git tag v1.0)
  workflow_dispatch:  # 手动触发选项

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Install UPX (可选的压缩工具)
      run: |
        $url = "https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip"
        Invoke-WebRequest -Uri $url -OutFile upx.zip
        Expand-Archive upx.zip -DestinationPath upx
        echo "$env:GITHUB_WORKSPACE\upx" | Out-File -FilePath $env:GITHUB_PATH -Append
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r src/requirements.txt
        
    - name: Build EXE
      run: |
        pyinstaller --noconfirm --clean --distpath dist --workpath build pyinstaller.spec
        Get-ChildItem -Path dist -Recurse
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nornir-netops
        path: dist/
