name: Build Windows EXE

on: [push]


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r src/requirements.txt
        
    - name: Build EXE
      run: |
        pyinstaller --distpath dist --onefile --console --name test.exe src/auto_netops.py
        Get-ChildItem -Path dist -Recurse
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nornir-netops
        path: dist/
